global:
  resolve_timeout: 5m

route:
  receiver: 'default-receiver'
  routes:
    - match:
        severity: 'warning'
      receiver: 'telegram'
    - match:
        severity: 'critical'
      receiver: 'discord'

receivers:
  - name: 'default-receiver'
    webhook_configs:
      - url: 'http://localhost:5000'  # Reemplaza con tu webhook si es necesario

  - name: 'telegram'
    telegram_configs:
      - bot_token: '7548600846:AAE_FizGmZycjOBlOsP6wV00siKRaohC95w'
        chat_id: 901311411  # Asegúrate de que el chat_id esté entre comillas
        message: |
          🛑 *Alerta* 🛑
          {{ range .Alerts }}
          *Alerta:* {{ .Annotations.summary }}
          *Descripción:* {{ .Annotations.description }}
          *Estado:* {{ .Status }}
          *Instancia:* {{ .Labels.instance }}
          {{ end }}

  - name: 'discord'
    webhook_configs:
      - url: 'https://discord.com/api/webhooks/1322546369583513640/Did_5xGGmwFKDkZkVEg5bXJqIwHwPBqsEOPJhHUJIyco1lvvAGxdCrCWH2OcbdLQsQr-'
        send_resolved: true
#      message: "Alerta crítica: {{ .Labels.instance }} está arriba"
