global:
  resolve_timeout: 5m

route:
  receiver: 'default-receiver'
  routes:
    - match:
        severity: 'warning'
      receiver: 'telegram'
    - match:
        severity: 'critical'
      receiver: 'discord'

receivers:
  - name: 'default-receiver'
    webhook_configs:
      - url: 'http://localhost:5000'  # Reemplaza con tu webhook si es necesario

  - name: 'telegram'
    telegram_configs:
      - bot_token: ''
        chat_id:   # Asegúrate de que el chat_id no esté entre comillas
        message: |
          🛑 *Alerta* 🛑
          {{ range .Alerts }}
          *Alerta:* {{ .Annotations.summary }}
          *Descripción:* {{ .Annotations.description }}
          *Estado:* {{ .Status }}
          *Instancia:* {{ .Labels.instance }}
          {{ end }}

  - name: 'discord'
    webhook_configs:
      - url: 'url_webhook_discord'
        send_resolved: true
#      message: "Alerta crítica: {{ .Labels.instance }} está arriba"
