groups:
  - name: cpu-usage-alerts
    rules:
      - alert: HighCPUUsage
        expr: avg by (instance) (rate(node_cpu_seconds_total{mode!="idle"}[1m])) * 100 > 1
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "High CPU Usage Detected"
          description: "CPU usage on instance {{ $labels.instance }} is {{ $value }}%."
  - name: cpu-usage-alerts-critical
    rules:
      - alert: HighCPUUsage
        expr: avg by (instance) (rate(node_cpu_seconds_total{mode!="idle"}[1m])) * 100 > 10
        labels:
          severity: critical
        annotations:
          summary: "High CPU Usage Detected"
          description: "CPU usage on instance {{ $labels.instance }} is {{ $value }}%."
